// <auto-generated />
namespace GoDeliverWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DeletedMigrations : IMigrationMetadata
    {
         

        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletedMigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "201811140920187_DeletedMigrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
