// <auto-generated />
namespace GoDeliverWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EnterDataForce : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnterDataForce));
        
        string IMigrationMetadata.Id
        {
            get { return "201811051353389_EnterData-Force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
